### ISSUE TITLE
License and contributing

### ISSUE THREAD

**Issue by arbesfeld** [ajvincent/es7-membrane#49]
Hey @ajvincent, great work on this project, it's fantastic! I would love to use this project in my other work and contribute. Is there any chance you could add a license to the repo?

**Comment by ajvincent** [comment]
@arbesfeld Sir, I would love to have contributions to this project, especially since my university studies have started again.  I'm going to be exceedingly busy until mid-December at least, so please, feel free to pick up issues as you see fit.  I do ask that you submit pull requests from your own fork, so I can do code reviews.  Also, if you want to review what I've already got, #7 is specifically one I can't do (as the original author:  one should not review one's own code for Production).

Bear in mind, though, I'm going to require a boatload of tests, as [spec/properties/](https://github.com/ajvincent/es7-membrane/blob/master/spec/properties/) implies.  The more combinations you can throw at it, the better!

I had started on #11, but per the comment I just added there, it needs a little rethinking.

Likewise, if you are working on a ticket that specifies an API which doesn't quite make sense, feel free to  implement what does make sense.  Implementation beats ticket-based specification here.

Also, if you want a formal contributor's guide (which wouldn't be a bad idea), file another ticket for that and I'll start one on the wiki when I can.
